spring:
  datasource:
    url: jdbc:h2:mem:crudproject;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  session:
    jdbc:
      store-type: jdbc
      table-name: SPRING_SESSION

  jpa:
    database: mysql
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true


  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
