name: Java CI with Gradle

on:
  push:
    branches: [ "deploy/githubactions","main"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'openjdk'

    - name: permission for gradlew    
      run : chmod +x ./back/board/gradlew
      
    - name: gradle build
      run : |
        cd back/board
        ./gradlew build -x test

    - name: exec
      run:
        nohup java -jar back/board/build/libs/project-0.0.1-SNAPSHOT.jar &
    
  
