name: Java CI with Gradle

on:
  push:
    branches: [ "deploy/githubactions","main"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: kill old server
      run : |
        killall -9 java || true    
    - name: permission for gradlew
      run : chmod +x ./back/board/gradlew

    - name: gradle build
      run : |
        cd back/board
        ./gradlew build
    - name: exec
      env:
        RUNNER_TRACKING_ID: ""
      run:
        nohup java -jar back/board/build/libs/project-0.0.1-SNAPSHOT.jar &
